# Generated by Django 3.0.8 on 2020-07-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='value',
            field=models.CharField(max_length=50, verbose_name='contact information'),
        ),
    ]
